// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        int64
	Uuid      string
	LoginID   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Storage struct {
	ID             int64
	GroupName      string
	StorageName    string
	ClearSlabQty   sql.NullInt64
	ClearBlockQty  sql.NullInt64
	CloudySlabQty  sql.NullInt64
	CloudyBlockQty sql.NullInt64
	CreatedAt      time.Time
}

type User struct {
	ID        int64
	LoginID   string
	PwHash    string
	CreatedAt time.Time
}
